# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import seamless_m4t_pb2 as seamless__m4t__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in seamless_m4t_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SeamlessM4TServiceStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpeechToText = channel.unary_unary(
                '/seamlessm4t.SeamlessM4TService/SpeechToText',
                request_serializer=seamless__m4t__pb2.SpeechToTextRequest.SerializeToString,
                response_deserializer=seamless__m4t__pb2.SpeechToTextResponse.FromString,
                _registered_method=True)


class SeamlessM4TServiceServicer(object):
    """Define the gRPC service
    """

    def SpeechToText(self, request, context):
        """Unary RPC for speech-to-text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeamlessM4TServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpeechToText': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechToText,
                    request_deserializer=seamless__m4t__pb2.SpeechToTextRequest.FromString,
                    response_serializer=seamless__m4t__pb2.SpeechToTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seamlessm4t.SeamlessM4TService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seamlessm4t.SeamlessM4TService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeamlessM4TService(object):
    """Define the gRPC service
    """

    @staticmethod
    def SpeechToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seamlessm4t.SeamlessM4TService/SpeechToText',
            seamless__m4t__pb2.SpeechToTextRequest.SerializeToString,
            seamless__m4t__pb2.SpeechToTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
