# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: seamless_m4t.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'seamless_m4t.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12seamless_m4t.proto\x12\x0bseamlessm4t\"6\n\x13SpeechToTextRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x10\n\x08tgt_lang\x18\x02 \x01(\t\"$\n\x14SpeechToTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2i\n\x12SeamlessM4TService\x12S\n\x0cSpeechToText\x12 .seamlessm4t.SpeechToTextRequest\x1a!.seamlessm4t.SpeechToTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seamless_m4t_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEECHTOTEXTREQUEST']._serialized_start=35
  _globals['_SPEECHTOTEXTREQUEST']._serialized_end=89
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_start=91
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_end=127
  _globals['_SEAMLESSM4TSERVICE']._serialized_start=129
  _globals['_SEAMLESSM4TSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
